apiVersion: v1
kind: Service
metadata:
    name: portfolio-ui
    namespace: production
spec:
    type: ClusterIP
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: portfolio-ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: portfolio-ui
spec:
    replicas: 3
    selector:
        matchLabels:
            app: portfolio-ui
    template:
        metadata:
            labels:
                app: portfolio-ui
        spec:
            containers:
                - name: portfolio-ui
                  image: registry.gitlab.com/mwcaisse/application-images/portfolio-ui:[[image_tag]]
                  ports:
                      - containerPort: 80
            imagePullSecrets:
                - name: docker-creds
