name: Build and Push image
description: Builds and pushes a docker image to a given container registry
inputs:
  registry:
    description: The registry to push the image to
    required: true
  username:
    description: The username to use to auth with the registry
    required: true
  password:
    description: The password to use to auth to the registry
    required: true
  tags:
    description: The tags to apply to the image
    required: true

runs:
  using: composite
  steps:
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v3

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ input.tags }}
