name: Build, Publish, and Deploy to Prod
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - run: yarn install
      - run: yarn lint

  build_publish:
    name: Build and Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Build and Publish
        uses: mwcaisse/gha-common/actions/build_and_push_image@master
        with:
          registry: registry.gitlab.com
          username: ${{ vars.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}
          tags: |
            registry.gitlab.com/mwcaisse/application-images/portfolio-ui:latest
            registry.gitlab.com/mwcaisse/application-images/portfolio-ui:${{ github.sha }}

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: build_publish
    environment: production
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Add the SHA to K8s template
        run: |
          sed -i 's/\[\[image_tag\]\]/${{ github.sha }}/g' k8s.prod.yml

      - name: Deploy to Kubernetes
        uses: mwcaisse/gha-common/actions/deploy_to_kubernetes@master
        with:
          deployment_file: k8s.prod.yml
          deployment_name: portfolio-ui
          namespace: production
          kubernetes_server: ${{ vars.KUBERNETES_SERVER }}
          kubernetes_ca: ${{ secrets.KUBERNETES_CA }}
          kubernetes_token: ${{ secrets.KUBERNETES_TOKEN_PROD }}
