name: Build, Publish, and Deploy to Prod
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - run: yarn install
      - run: yarn lint
  build_publish:
    name: Build and Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitlab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com/
          username: ${{ vars.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            registry.gitlab.com/mwcaisse/application-images/portfolio-ui:latest
            registry.gitlab.com/mwcaisse/application-images/portfolio-ui:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build_publish
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Add the SHA to K8s template
        run: |
          sed -i 's/[[image_tag]]/${{ github.sha }}/g` k8s.prod.yml

      - name: Deploy to K8s
        run: |          
          echo "${{ secrets.KUBERNETES_CA }} >> /tmp/k8s_ca
          kubectl --certificate-authority="/tmp/k8s_ca" --server=${{ vars.KUBERNETES_SERVER }} --token=${{ secrets.KUBERNETES_TOKEN_PROD }} --namespace=production apply -f k8s.prod.yml

      - name: Verify Deployment
        run: |
          echo "${{ secrets.KUBERNETES_CA }} >> /tmp/k8s_ca
          kubectl --certificate-authority="/tmp/k8s_ca" --server=${{ vars.KUBERNETES_SERVER }} --token=${{ secrets.KUBERNETES_TOKEN_PROD }} --namespace=production rollout status deployment/portfolio-ui

